services:
  - type: web
    name: friendus
    env: docker # Chuyển sang Docker để dùng Dockerfile tối ưu ở trên
    plan: free
    region: singapore # Chọn vùng gần VN để load nhanh hơn

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: ENABLE_SEED
        value: "True" # Đổi thành False nếu không muốn reset data mỗi lần deploy
      - key: TZ
        value: "Asia/Ho_Chi_Minh"